# Generated by Django 5.1.3 on 2024-11-18 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkedin_email', models.EmailField(max_length=254)),
                ('linkedin_password_encrypted', models.TextField()),
                ('remote_jobs', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('fewer_applicants', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10)),
                ('experience_level', models.JSONField(default=dict)),
                ('job_type', models.JSONField(default=dict)),
                ('job_posting_date', models.CharField(default='All Time', max_length=20)),
                ('job_positions', models.JSONField(default=list)),
                ('job_locations', models.JSONField(default=list)),
                ('resident_status', models.BooleanField(default=True)),
                ('distance_from_job_location', models.CharField(max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('cover_letter', models.FileField(blank=True, null=True, upload_to='cover_letters/')),
                ('has_driver_license', models.BooleanField(default=True)),
                ('requires_sponsorship', models.BooleanField(default=False)),
                ('pronouns', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('linkedin_profile', models.URLField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
