# Generated by Django 5.1.3 on 2024-12-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.JSONField(default=dict),
        ),
    ]
