# Generated by Django 5.1.3 on 2024-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_locations',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_positions',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_posting_date',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='job_type',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='LinkedIn_Profile',
            field=models.TextField(default='https://www.linkedin.com/in/john-doe/', max_length=80),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Minimum_Salary_Expectation',
            field=models.TextField(default='32000', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Notice_Period',
            field=models.TextField(default='3', max_length=5),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Posting_Date',
            field=models.CharField(choices=[('All_Time', 'All_Time'), ('month', 'month'), ('week', 'week'), ('24_hours', '24_hours')], default='All_Time', max_length=15),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='University_gpa',
            field=models.TextField(blank=True, default='A', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Years_of_Experience_1',
            field=models.TextField(default='Software Developer : 3', max_length=35),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Years_of_Experience_2',
            field=models.TextField(blank=True, default='python : 2', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Years_of_Experience_3',
            field=models.TextField(blank=True, default='sql : 8', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Years_of_Experience_4',
            field=models.TextField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='authorized_to_work',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='background_check',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='citizenship',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='city',
            field=models.TextField(default='London', max_length=40),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='comfortable_with_commuting',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='comfortable_with_remote_work',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='complete_an_assessment',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='completed_Degree',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='disability_status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='drug_test',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_associate',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_director',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_entry',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_executive',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_internship',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience_mid_Senior',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='first_Name',
            field=models.TextField(default='John', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_location_1',
            field=models.TextField(default='England', max_length=30),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_location_2',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_location_3',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_location_4',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_location_5',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_location_6',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_position_1',
            field=models.TextField(default='python developer', max_length=30),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_position_2',
            field=models.TextField(default='digital marketer', max_length=30),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_position_3',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_position_4',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_position_5',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='job_position_6',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobtype_contract',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobtype_fulltime',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobtype_internship',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobtype_parttime',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobtype_temprory',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='jobtype_volunteer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='language_1',
            field=models.TextField(default='English', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='language_2',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='language_3',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='last_Name',
            field=models.TextField(default='Doe', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='message_to_hire',
            field=models.CharField(blank=True, default='Doe', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='necessary_licenses',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='race',
            field=models.TextField(default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='security_clearance',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='start_immediately',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='state',
            field=models.TextField(default='London', max_length=40),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='street_address',
            field=models.TextField(default='wimbley street', max_length=40),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='veteran_status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='Yes', max_length=10),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='website',
            field=models.TextField(blank=True, default='https://www.johndoe.com/', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='zip_code',
            field=models.TextField(default='0WB ACE', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='distance_from_job_location',
            field=models.CharField(choices=[('0', '0'), ('5', '5'), ('10', '10'), ('25', '25'), ('50', '50'), ('100', '100')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='fewer_applicants',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='has_driver_license',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='requires_sponsorship',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='resident_status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='Yes', max_length=10),
        ),
    ]
