# Generated by Django 5.1.3 on 2024-11-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='Years_of_Experience_10',
            field=models.TextField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Years_of_Experience_5',
            field=models.TextField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Years_of_Experience_6',
            field=models.TextField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Years_of_Experience_7',
            field=models.TextField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Years_of_Experience_8',
            field=models.TextField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='Years_of_Experience_9',
            field=models.TextField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='distance_from_job_location',
            field=models.CharField(choices=[('0', '0'), ('5', '5'), ('10', '10'), ('25', '25'), ('50', '50'), ('100', '100')], default='25', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=models.TextField(default='+447012345678', max_length=15),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='remote_jobs',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes', max_length=10),
        ),
    ]
