# Generated by Django 5.1.3 on 2024-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_jobapplication_years_of_experience_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='phone_country_code',
            field=models.TextField(default='+44', max_length=15),
        ),
    ]
