# Generated by Django 5.1.3 on 2024-11-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_remove_jobapplication_experience_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='linkedin_profile',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=models.TextField(default='+447012345678', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='pronouns',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary.', 'Non-binary'), ('Other', 'Other')], max_length=30),
        ),
    ]
