# Generated by Django 5.1.3 on 2024-11-28 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_auto_20241127_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='checkboxes_completed_Degree',
            new_name='degreeCompleted',
        ),
    ]
