# Generated by Django 5.1.3 on 2024-11-19 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_remove_jobapplication_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='LinkedIn_Profile',
            new_name='Linkedin_Profile',
        ),
    ]
