# Generated by Django 5.1.3 on 2024-11-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0003_jobapplication_phone_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='pronouns_us',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Non-binary.', 'Non-binary'), ('Other', 'Other')], default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='message_to_hire',
            field=models.CharField(blank=True, default='Hi, I am interested to join your organization. Please have a look at my resume. Thank you.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='pronouns',
            field=models.CharField(choices=[('Mr.', 'Mr.'), ('Ms.', 'Ms.'), ('Mx.', 'Mx.'), ('etc.', 'etc.')], max_length=10),
        ),
    ]
