# Generated by Django 5.1.3 on 2024-11-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_jobapplication_pronouns_us_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='security_clearance_us',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='Yes', max_length=10),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='security_clearance',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=10),
        ),
    ]
