# Generated by Django 5.1.3 on 2024-12-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0004_jobapplication_experience_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
