# Generated by Django 5.1.3 on 2024-12-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0005_jobapplication_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='useremail',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
