# Generated by Django 5.1.3 on 2024-11-20 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0005_jobapplication_security_clearance_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='Linkedin_Profile',
            field=models.CharField(default='https://www.linkedin.com/in/john-doe/', max_length=80),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Minimum_Salary_Expectation',
            field=models.CharField(default='32000', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Notice_Period',
            field=models.CharField(default='3', max_length=5),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='University_gpa',
            field=models.CharField(blank=True, default='A', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Years_of_Experience_1',
            field=models.CharField(default='Software Developer : 3', max_length=35),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Years_of_Experience_10',
            field=models.CharField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Years_of_Experience_2',
            field=models.CharField(blank=True, default='python : 2', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Years_of_Experience_3',
            field=models.CharField(blank=True, default='sql : 8', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Years_of_Experience_4',
            field=models.CharField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Years_of_Experience_5',
            field=models.CharField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Years_of_Experience_6',
            field=models.CharField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Years_of_Experience_7',
            field=models.CharField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Years_of_Experience_8',
            field=models.CharField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='Years_of_Experience_9',
            field=models.CharField(blank=True, default='aws : 3', max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='city',
            field=models.CharField(default='London', max_length=40),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='first_Name',
            field=models.CharField(default='John', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_location_1',
            field=models.CharField(default='England', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_location_2',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_location_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_location_4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_location_5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_location_6',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_position_1',
            field=models.CharField(default='python developer', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_position_2',
            field=models.CharField(default='digital marketer', max_length=30),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_position_3',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_position_4',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_position_5',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='job_position_6',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='language_1',
            field=models.CharField(default='English', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='language_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='language_3',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='last_Name',
            field=models.CharField(default='Doe', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_country_code',
            field=models.CharField(default='+44', max_length=15),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='phone_number',
            field=models.CharField(default='+447012345678', max_length=15),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='race',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='state',
            field=models.CharField(default='London', max_length=40),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='street_address',
            field=models.CharField(default='wimbley street', max_length=40),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='website',
            field=models.CharField(blank=True, default='https://www.johndoe.com/', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='zip_code',
            field=models.CharField(default='0WB ACE', max_length=20),
        ),
    ]
