# Generated by Django 5.1.3 on 2024-11-26 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0007_alter_jobapplication_pronouns_us'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='linkedin_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='linkedin_password_encrypted',
            new_name='password',
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='website',
            field=models.URLField(blank=True, default='https://www.johndoe.com/', max_length=50, null=True),
        ),
    ]
