# Generated by Django 5.1.3 on 2024-11-26 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0008_rename_linkedin_email_jobapplication_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='email',
            new_name='linkedinEmail',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='password',
            new_name='linkedinPassword',
        ),
    ]
